import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/feature/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SML Nom Market",
  description: "Generated by create next app",
  openGraph: {
    title: "SML Nom Market",
    description: "Generated by create next app",
    url: "https://sml-nom-market.vercel.app/",
    siteName: "SML Nom Market",
    images: [
      {
        url: "https://sml-nom-market.vercel.app/assets/logosml.png",
        width: 1200,
        height: 630,
        alt: "SML Nom Market Logo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "SML Nom Market",
    description: "Generated by create next app",
    images: ["https://sml-nom-market.vercel.app/assets/logosml.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
